## NUMPY (NUMERICAL PYTHON)
- Fundational package for numerical computing in python
- It provides an ndarry object which is an efficient multidimentinal array providing fast array oriented operations
- Provides a lot of function

In [3]:
import numpy as np

### CREATING NDARRAYS
- CREATING NDARRAYS FROM AN OBJECT

In [5]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [5]:
type(a1)

numpy.ndarray

In [6]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [6]:
type(a1)

numpy.ndarray

In [16]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a2 = np.array(range(2,11,2))
a2

array([ 2,  4,  6,  8, 10])

In [31]:
a2.ndim            # To get the dimention of aaray

1

In [32]:
a2.shape

(5,)

In [36]:
a3 = np.array([[1,2,3],[4,5,6]])
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a3.ndim

2

In [38]:
a3.shape

(2, 3)

In [11]:
a4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
a4.shape

(1, 3, 3)

In [46]:
a4.ndim

3

In [4]:
a2 = np.array([[[1,2,3],[4,5,6]]])
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [6]:
a2.shape

(1, 2, 3)

In [7]:
a2.ndim

3

In [4]:
a4 = np.array([[[1,2,3],[4,5,6],[7,8,9],[4,5,3]]])
a4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [4, 5, 3]]])

In [7]:
a4.shape

(1, 4, 3)

In [8]:
a4.ndim

3

In [16]:
a2 = np.array([[[[1,2,3],[4,5,6]]]])
a2

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [17]:
a2.shape

(1, 1, 2, 3)

In [11]:
a2.ndim

4

In [12]:
a1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
a1.shape

(2, 2, 2)

In [15]:
a1.ndim

3

In [24]:
a2 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
a2

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [25]:
a2.shape

(1, 4, 2)

In [26]:
a2.ndim

3

In [28]:
a3 = np.array([[[1,2],[3,4,5],[5,6],[7,8]]])                   # Elements no. shuould be same
a3

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.

### CREATING NDARRAY OF ONES, ZEROES AND SPECIFIC VALUES

In [32]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.ones((5,6),dtype=int)           # 2d array

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [34]:
np.ones((3,2,4))                   # 3d array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
np.ones(4)                         # 1d array

array([1., 1., 1., 1.])

In [39]:
np.full((4,5),fill_value=5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [44]:
np.eye(5)                        # Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## OPERATIONS ON NDARRAYS

In [53]:
l = [1,2,3,4]
l+[2]

[1, 2, 3, 4, 2]

In [55]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [56]:
a+2                 # This is only possible in array

array([3, 4, 5, 6])

In [58]:
b = np.array([4,5,6,7])
b

array([4, 5, 6, 7])

In [61]:
a+b

array([ 5,  7,  9, 11])

In [62]:
a-b

array([-3, -3, -3, -3])

In [63]:
a*b

array([ 4, 10, 18, 28])

In [64]:
a/b

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [68]:
b/a

array([4.  , 2.5 , 2.  , 1.75])

In [65]:
a//b

array([0, 0, 0, 0])

In [66]:
a%b

array([1, 2, 3, 4])

In [67]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [69]:
a**2

array([ 1,  4,  9, 16])

In [70]:
b**2

array([16, 25, 36, 49])

In [71]:
2/a

array([2.        , 1.        , 0.66666667, 0.5       ])

In [74]:
a

array([1, 2, 3, 4])

In [75]:
b

array([4, 5, 6, 7])

In [72]:
a>b

array([False, False, False, False])

In [73]:
b>a

array([ True,  True,  True,  True])

## INDEXING AND SLICING IN DIMENSION ARRAY

In [78]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a[7]

7

In [80]:
a[-1]

9

In [81]:
a[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [82]:
a[-10]

0

In [83]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a[-8:-3]

array([2, 3, 4, 5, 6])

In [90]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## RESHAPE AND TRANSPOSE
- RESHAPE : CONVERTING TO2D, 3D, 4D ARRAY
- TRANSPOSE : CONVERTING ROWS INTO COLUMN

In [4]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a.ndim

1

In [6]:
a.shape

(16,)

In [8]:
a = a.reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a = a.reshape((8,2))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [10]:
a = a.reshape((2,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [11]:
a = a.reshape((1,16))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [12]:
a= a.reshape((16,1))
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [13]:
a = a.reshape((4,2,2))
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [14]:
a = a.reshape((2,2,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [15]:
a = a.reshape((2,4,2))
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [16]:
a = a.reshape((8,2,1))
a

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [17]:
a = a.reshape((8,1,2))
a

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]],

       [[12, 13]],

       [[14, 15]]])

In [18]:
a = a.reshape((2,1,8))
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]]])

In [19]:
a = a.reshape((1,4,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
a = a.reshape((4,1,4))
a

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]],

       [[12, 13, 14, 15]]])

In [21]:
a = a.reshape((4,4,1))
a             

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]]])

In [24]:
a = a.reshape((1,4,2,2))
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### TRANSPOSE

In [28]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

### FUNCTION

In [30]:
a = np.array([2,3,6,4,5,9,8,7,1,0])
a

array([2, 3, 6, 4, 5, 9, 8, 7, 1, 0])

In [32]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
np.cbrt(s)

array([0.        , 1.        , 1.58740105, 2.08008382, 2.5198421 ,
       2.92401774, 3.30192725, 3.65930571, 4.        , 4.32674871])

In [39]:
np.abs([-1,-2,4,5,-7,-7])

array([1, 2, 4, 5, 7, 7])

In [40]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [42]:
np.subtract([1,2,3],[4,5,6])

array([-3, -3, -3])

In [43]:
np.multiply([1,2,3],[4,5,6])

array([ 4, 10, 18])

In [13]:
np.divide([1,2,3],[4,5,6])

array([0.25, 0.4 , 0.5 ])

In [40]:
p = np.array([2,1,4,5,3,6])
p

array([2, 1, 4, 5, 3, 6])

In [39]:
q = np.array([3,4,2,1,6,5])
q

array([3, 4, 2, 1, 6, 5])

In [32]:
np.minimum(p,q)

array([2, 1, 2, 1, 3, 5])

In [33]:
np.maximum(p,q)

array([3, 4, 4, 5, 6, 6])

In [34]:
np.greater(p,q)

array([False, False,  True,  True, False,  True])

In [41]:
np.greater(q,p)

array([ True,  True, False, False,  True, False])

In [36]:
np.less(p,q)

array([ True,  True, False, False,  True, False])

In [42]:
np.less(q,p)

array([False, False,  True,  True, False,  True])

In [22]:
ar1 = np.arange(21)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

#### FOR ONR DIMENSION ARRAY -

In [23]:
ar1.mean()

10.0

In [26]:
np.median(ar1)

10.0

In [30]:
ar1.min()

0

In [28]:
ar1.max()

20

In [29]:
ar1.sum()

210

#### FOR TWO DIMENSION ARRAY -

In [43]:
a = np.arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [44]:
a = a.reshape((8,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [37]:
a.shape

(8, 8)

In [38]:
a.mean()

31.5

In [39]:
np.median(a)

31.5

In [42]:
a.mean(axis=0)            # Getting mean by vertically

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [43]:
a.mean(axis=1)            # Getting mean by Horizontally

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [44]:
a.max()

63

In [45]:
a.max(axis=0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [46]:
a.max(axis=1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [47]:
a.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
a.min(axis=1)

array([ 0,  8, 16, 24, 32, 40, 48, 56])

In [53]:
#*** MOST IMP Q. ASKED IN INTERVIWS

x = np.array([1,2,4,3,3,4])
x

array([1, 2, 4, 3, 3, 4])

In [54]:
np.argmax(x)                # This is giving the index of maximum(grater) value

2

In [55]:
np.argmin(x)              # This is giving the index of minimum(small) value

0

In [45]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.argmax(a)

8

In [59]:
np.argmin(a)

0

In [8]:
a1 = np.array([2,1,5,4,3,5,6,7,3,9,2,3]).reshape(3,4)
a1

array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [9]:
np.argmax(a1)

9

In [10]:
np.argmin(a1)

1

In [75]:
np.argmax(a1,axis=0)

array([1, 2, 1, 1], dtype=int64)

In [76]:
np.argmin(a1,axis=0)

array([0, 0, 2, 2], dtype=int64)

In [77]:
np.argmax(a1,axis=1)

array([2, 3, 1], dtype=int64)

In [78]:
np.argmin(a1,axis=1)

array([1, 0, 2], dtype=int64)

In [12]:
a2 = a1.reshape(1,3,4)
a2

array([[[2, 1, 5, 4],
        [3, 5, 6, 7],
        [3, 9, 2, 3]]])

In [13]:
a2 = a1.squeeze()
a2

array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [48]:
a1 = np.arange(5)
a2 = np.arange(5,10)
print(a1)


[0 1 2 3 4]


In [49]:
print(a2)

[5 6 7 8 9]


In [17]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a1= a1.reshape(1,5)
a1

array([[0, 1, 2, 3, 4]])

In [19]:
a2 = a2.reshape(1,5)
a2

array([[5, 6, 7, 8, 9]])

In [21]:
np.concatenate((a1,a2), axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
np.concatenate((a1,a2), axis = 1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## RANDOM NUMBERS

In [31]:
np.random.randint(1,100)               # if range is not given it will give only 1 random value

25

In [32]:
np.random.randint(1,100,10)            # last 10 is showing the range of numbers we want

array([83, 99, 40, 61, 94, 64, 49, 18, 45, 42])

In [33]:
np.random.randint(1,100,(10,10))

array([[93, 75, 34, 63, 59, 23, 93, 18, 75, 83],
       [40, 53, 29, 40, 15, 15, 75, 53, 82, 93],
       [49, 28, 91, 94, 40,  5, 81, 64, 42, 74],
       [ 2, 51, 42, 32, 78, 30, 13, 77,  6, 43],
       [64, 87, 99, 25, 71, 28, 93, 37, 32, 50],
       [26, 41,  5, 44, 38, 70, 58, 81, 65, 53],
       [48, 63, 42, 30, 88, 90, 64, 92, 99, 64],
       [64, 72, 76, 33, 99, 79,  3, 36, 13, 85],
       [33, 77, 28, 11, 37,  9, 33, 54, 98, 62],
       [ 2, 97, 97, 86, 42, 69, 81, 11, 48,  8]])

In [34]:
np.random.randint(1,100,(10,10))

array([[58, 98, 50, 58, 27, 73, 85, 88, 58, 95],
       [65, 45, 80, 87, 17, 39, 97, 54, 68, 56],
       [14, 28, 74, 67, 16, 58, 20, 81, 95, 64],
       [72, 60, 23, 31, 74, 34, 72, 19, 54, 67],
       [90, 18, 84, 33, 37, 27,  2, 46, 56, 72],
       [21, 47, 65, 18, 27, 75,  2, 37, 42, 81],
       [45, 26, 76, 12, 86, 15,  6, 73, 67, 22],
       [95, 58, 78, 60, 48,  8, 91, 51, 34, 87],
       [61, 68, 61, 46,  9, 15, 14, 15, 16, 99],
       [82, 68, 29, 35, 57, 53, 20, 41, 33, 54]])

In [35]:
np.random.rand(10)               # For float values

array([0.56527804, 0.771809  , 0.43229516, 0.43766925, 0.47105998,
       0.6647445 , 0.56920538, 0.49872081, 0.6229407 , 0.34527674])

In [37]:
np.random.rand(10,5)                      # In 2d array

array([[0.1277128 , 0.70818639, 0.03776037, 0.54405649, 0.12385631],
       [0.0780547 , 0.28844512, 0.23026372, 0.00670871, 0.01040693],
       [0.26364321, 0.00284042, 0.38002332, 0.77075141, 0.83367151],
       [0.75540816, 0.09235465, 0.38333444, 0.55642116, 0.07703773],
       [0.20519386, 0.78576754, 0.85542463, 0.59552265, 0.33356398],
       [0.42204293, 0.36977557, 0.63637432, 0.2284662 , 0.82035076],
       [0.47133487, 0.87298224, 0.89101046, 0.94315157, 0.03401934],
       [0.06184244, 0.99084323, 0.93330608, 0.06349632, 0.98387692],
       [0.03191568, 0.58072343, 0.55581789, 0.83881076, 0.77388467],
       [0.91941104, 0.75234594, 0.08779697, 0.2636224 , 0.27589413]])

In [38]:
np.random.randn(10)                     # This will include negative values as well

array([-1.3537645 ,  0.84955577, -0.55991456,  1.650239  ,  0.75328141,
       -0.39598224,  0.14724394,  0.07783201, -1.3717498 ,  0.50273602])

In [39]:
np.random.randn(10,4)

array([[-0.25203358,  1.14590984, -0.29176221, -0.29008928],
       [ 1.04433568, -1.12504505,  0.04858381, -0.85694386],
       [-2.60185569, -0.90046133,  0.41362262,  2.07235005],
       [-0.63558251, -0.21397144,  1.39190588, -0.67850191],
       [ 0.59668328,  0.87238182, -0.10233232,  0.13404143],
       [ 0.60193704,  1.41345167,  0.4776848 ,  0.90077094],
       [-0.50915759,  1.2073375 ,  0.10833363,  1.03911758],
       [-1.9326648 , -1.42464727, -0.84317229, -0.430293  ],
       [ 1.269398  ,  1.41269093,  0.28425065, -0.20795535],
       [-0.59267406,  1.57206381, -0.58064855,  0.58699303]])

## CONDITIONAL INDEXING

In [49]:
a = np.random.randint(1,100,(8,8))
a

array([[23, 85, 19, 49, 20, 69, 24, 35],
       [55, 63, 98, 98, 70, 70, 55, 23],
       [54, 88, 21,  8,  4, 83, 34,  7],
       [94, 26, 61, 40, 19, 20, 21, 35],
       [67, 51, 15, 53, 54, 12, 24, 62],
       [34, 86, 20, 16, 97, 74, 87, 84],
       [25, 58, 26, 16,  8,  2, 21, 13],
       [84, 63, 86, 12, 40, 62, 41, 46]])

In [50]:
a[a>50]

array([85, 69, 55, 63, 98, 98, 70, 70, 55, 54, 88, 83, 94, 61, 67, 51, 53,
       54, 62, 86, 97, 74, 87, 84, 58, 84, 63, 86, 62])

In [51]:
a[a<50]

array([23, 19, 49, 20, 24, 35, 23, 21,  8,  4, 34,  7, 26, 40, 19, 20, 21,
       35, 15, 12, 24, 34, 20, 16, 25, 26, 16,  8,  2, 21, 13, 12, 40, 41,
       46])

In [53]:
a[a==50]

array([], dtype=int32)

### SLICING IN MULTIDIMENTIONAL ARRAY

In [54]:
a = np.random.randint(1,100,(10,10))
a

array([[30, 73,  8, 90, 40, 73,  4, 81, 86, 60],
       [16, 25,  4,  4, 73, 21, 55, 55,  6,  4],
       [83, 51, 97,  9, 15, 29, 70, 40, 16, 63],
       [98, 13, 73, 68, 34, 96, 67, 62, 78, 10],
       [80, 92,  5, 40, 11, 77, 98, 53, 71, 11],
       [27, 50, 75, 97, 81, 59, 58, 43, 36, 89],
       [92, 54, 36, 87, 82, 81, 83, 16, 51, 71],
       [69, 49, 85, 59, 99, 19, 45, 63, 98, 66],
       [ 7, 40, 92, 26, 57, 48, 14, 38, 19, 24],
       [94, 79,  4, 13, 53, 89, 57, 93, 56, 88]])

In [55]:
a[2][4]

15

In [56]:
a[3:5][:]

array([[98, 13, 73, 68, 34, 96, 67, 62, 78, 10],
       [80, 92,  5, 40, 11, 77, 98, 53, 71, 11]])

In [57]:
a[3:5,:]

array([[98, 13, 73, 68, 34, 96, 67, 62, 78, 10],
       [80, 92,  5, 40, 11, 77, 98, 53, 71, 11]])

In [58]:
a[1:3,5:8]            # first 2 values are for row and second 2 values se for column

array([[21, 55, 55],
       [29, 70, 40]])

In [59]:
a[3:10:3,3:8:2]

array([[68, 96, 62],
       [87, 81, 16],
       [13, 89, 93]])